### PR TITLE
Added Query form

### PR DESCRIPTION
**Pull request by Amritanshu02**

### CODE REVIEW

**Comment by avinash201199** [comment]
image
you have done very minor chane , you can improve contact us page , fil the information where required , I have provided my all details . Remove the error image.

**Comment by avinash201199** [comment]
image

Remove the map code ,not required

**Comment by Amritanshu02** [comment]
Yeah Sure, I will update it more

**Comment by avinash201199** [comment]
> Yeah Sure, I will update it more

Thank you :)

**Comment by avinash201199** [comment]
Fork again :)
and then make pr

**Pull request closed without merging**
