### PR TITLE
Changes_in_gallery-section

### PR DESCRIPTION
**Pull request by Rositasikarwar**
Hi, I have modified the gallery section. 
The pictures early were not categorized according to the title.
so I have changed them with high-quality images 
check this out-

INITIAL PICTURES----------------
Screenshot 2022-10-09 10 06 08
Screenshot 2022-10-09 10 06 11
Screenshot 2022-10-09 10 06 14

MODIFIED PICTURES----------------
Screenshot 2022-10-09 10 05 42
Screenshot 2022-10-09 10 05 47
Screenshot 2022-10-09 10 05 50

### CODE REVIEW

**Comment by avinash201199** [comment]
hey , I want to add images which are taken by me 
 you can take images from my instagram page - https://www.instagram.com/my_gallery_4u/
at last I have to change the images with mine one , so can you please add my images

**Comment by avinash201199** [comment]
some images are here - https://github.com/avinash201199/My-Gallery-4u/tree/master/my%20image

**Comment by avinash201199** [comment]
waiting for your pr

**Comment by Rositasikarwar** [comment]
I will definitely try to complete the task as soon as possible before tonight.

**Comment by avinash201199** [comment]
Thank you for your effort Roshita :)

**Comment by avinash201199** [comment]
for now closing the pr  you can make new pr :)

**Pull request closed without merging**
