### PR TITLE
Fixed contact us button in about page

### LINKED ISSUE #44: Contact us button not working in about page
contact us button  in about page should redirect user to contact page

### PR DESCRIPTION
**Pull request by GulshanKataria**
Fixes #44 

Fixed contact us button in about page

### CODE REVIEW

**Comment by avinash201199** [comment]
do not make too many pr in same repo ,try to contribute in other repo as well :)

**Comment by GulshanKataria** [comment]
> do not make too many pr in same repo ,try to contribute in other repo as well :)

Yes  sure . I am trying in other repos as well. Thank you :)

**Comment by avinash201199** [comment]
> > do not make too many pr in same repo ,try to contribute in other repo as well :)
> 
> Yes sure . I am trying in other repos as well. Thank you :)

https://github.com/avinash201199/Paid-Internship-List

**Comment by GulshanKataria** [comment]
> > > do not make too many pr in same repo ,try to contribute in other repo as well :)
> > 
> > 
> > Yes sure . I am trying in other repos as well. Thank you :)
> 
> https://github.com/avinash201199/Paid-Internship-List

Thank you very much @avinash201199

**Comment by avinash201199** [comment]
welcome :)
follow for more

**Pull request merged**
