### PR TITLE
Hey, I have replaced default images with yours. If you want to make any changes, let me know I will edit it. Thanks.

### PR DESCRIPTION
**Pull request by yamini3707**

### CODE REVIEW

**Comment by yamini3707** [comment]
Screenshot (27)

**Comment by yamini3707** [comment]
Screenshot (29)


Hey,I hope this is fine. If you still want to make any changes, let me know, I will edit it.

**Comment by avinash201199** [comment]
image
there is a repeatation , please correct it :)

**Comment by yamini3707** [comment]
> @yamini3707 You have done great job Yamini :) please be connected reach me here -https://www.instagram.com/lets__code/

Thanks :)

**Pull request merged**
