### PR TITLE
Footer made responsive

### PR DESCRIPTION
**Pull request by shiyasmohd**
Footer wasn't responsive for mobile and tablet view. cleared them all and made little changes in appearance.

### CODE REVIEW

**Comment by avinash201199** [comment]
please add screen shot

**Comment by Shiyasmohd** [comment]
> please add screen shot
Screenshot 2021-10-10 170014
Screenshot 2021-10-10 170100
Screenshot 2021-10-10 170143

**Comment by avinash201199** [comment]
hey , index page footer is already responsive ,please copy paste it on other pages , will accept your pr :)
image


image

**Comment by Shiyasmohd** [comment]
g1
g2
this is from blog page...like this for all page has been done

**Pull request closed without merging**
